{% set version = "3.8" %}

package:
  name: nltk
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nltk/nltk-{{ version }}.zip
  sha256: 74b30826a37d78d53427105bbd037dd880251be269fca64ee530838a46ed55fc

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - nltk = nltk.cli:cli

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - click
    - joblib
    - regex >=2021.8.3
    - tqdm

test:
  imports:
    - nltk
    - nltk.app
    - nltk.ccg
    - nltk.chat
    - nltk.chunk
    - nltk.classify
    - nltk.cluster
    - nltk.corpus
    - nltk.corpus.reader
    - nltk.draw
    - nltk.inference
    - nltk.lm
    - nltk.metrics
    - nltk.misc
    - nltk.parse
    - nltk.sem
    - nltk.sentiment
    - nltk.stem
    - nltk.tag
    - nltk.tbl
    - nltk.test
    - nltk.test.unit
    - nltk.test.unit.translate
    - nltk.tokenize
    - nltk.translate
    - nltk.twitter
  requires:
    - pip
  commands:
    - pip check
    - nltk --help

about:
  home: http://nltk.org/
  license_file: LICENSE.txt
  license: Apache-2.0
  license_family: Apache
  summary: Natural Language Toolkit
  dev_url: https://github.com/nltk/nltk
  doc_url: http://www.nltk.org/

extra:
  recipe-maintainers:
    - quartox
    - synapticarbors
