{% set version = "3.6.2" %}

package:
  name: nltk
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/n/nltk/nltk-{{ version }}.zip
  sha256: 57d556abed621ab9be225cc6d2df1edce17572efb67a3d754630c9f8381503eb

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - nltk = nltk.cli:cli

requirements:
  host:
    - python >=3.5
    - pip
  run:
    - python >=3.5
    - click
    - joblib
    - regex
    - tqdm

test:
  imports:
    - nltk
    - nltk.app
    - nltk.ccg
    - nltk.chat
    - nltk.chunk
    - nltk.classify
    - nltk.cluster
    - nltk.corpus
    - nltk.corpus.reader
    - nltk.draw
    - nltk.inference
    - nltk.lm
    - nltk.metrics
    - nltk.misc
    - nltk.parse
    - nltk.sem
    - nltk.sentiment
    - nltk.stem
    - nltk.tag
    - nltk.tbl
    - nltk.test
    - nltk.test.unit
    - nltk.test.unit.translate
    - nltk.tokenize
    - nltk.translate
    - nltk.twitter
  commands:
    - nltk -h

about:
  home: http://nltk.org/
  license_file: LICENSE.txt
  license: Apache-2.0
  license_family: Apache
  summary: Natural Language Toolkit
  dev_url: https://github.com/nltk/nltk
  doc_url: http://www.nltk.org/

extra:
  recipe-maintainers:
    - pmlandwehr
    - quartox
    - synapticarbors
